<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Taxi Request List</name>
   <tag></tag>
   <elementGuidId>a407909d-7c12-41ad-9513-5d4016465218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mxui_widget_HorizontalScrollContainer_0']/div[2]/div/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.mx-text.mx-name-text3.headerhero-title.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>071ab61d-e92b-4e92-b0ef-85ce1dc2b0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-text mx-name-text3 headerhero-title text-white</value>
      <webElementGuid>6b13e6fc-6075-4615-8b78-ab88c57577a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Taxi Request List</value>
      <webElementGuid>7137c15d-3649-4ae3-8c3d-84ad76ad82cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_HorizontalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-center region-content&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-placeholder&quot;]/div[@class=&quot;mx-name-container2 headerhero text-center col-center spacing-outer-bottom-large&quot;]/div[@class=&quot;mx-name-container3 heroheader-overlay&quot;]/h1[@class=&quot;mx-text mx-name-text3 headerhero-title text-white&quot;]</value>
      <webElementGuid>5826b14a-8a14-4d00-963e-1f4fc9f3af55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_HorizontalScrollContainer_0']/div[2]/div/div/div/div/h1</value>
      <webElementGuid>d00001b9-56a2-41e4-9d01-be6927cde89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task name'])[1]/preceding::h1[1]</value>
      <webElementGuid>d785bf06-efde-47de-9a3b-56145c82f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due by'])[1]/preceding::h1[1]</value>
      <webElementGuid>c5f49193-f233-4e38-9e17-04da6de3caad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Taxi Request List']/parent::*</value>
      <webElementGuid>6d50d47e-1749-4c0a-bf57-6f9300c3e80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c48136f4-e5bd-4dda-8324-b3d8fc1435c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Taxi Request List' or . = 'Taxi Request List')]</value>
      <webElementGuid>b64c4322-62c2-42d9-82c2-e7aaf46fd19d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
