<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_100.TaxiRequisition.LoginPag_7a5430</name>
   <tag></tag>
   <elementGuidId>11846d9a-7a43-46ee-af0a-10755a5e3a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='100.TaxiRequisition.LoginPage.passwordTextBox2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7566f437-4a45-42a5-b160-ec0aeac75199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ebfda7dd-c797-418e-8e3e-685bc0583cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>100.TaxiRequisition.LoginPage.passwordTextBox2</value>
      <webElementGuid>37fe5f98-684e-4567-a444-b9e0f4593dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58d8d90f-f94e-448f-bd7b-b1e225f3e7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2aed7cb8-3d04-47d7-9157-a21454d0065a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4d657ad-ab14-442d-8f82-6b036ebdc077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a6b5f01c-8d51-4ca2-8094-c7acc12fb95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;100.TaxiRequisition.LoginPage.passwordTextBox2&quot;)</value>
      <webElementGuid>deb779d1-2e84-4235-b9a9-190aed7e37f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='100.TaxiRequisition.LoginPage.passwordTextBox2']</value>
      <webElementGuid>396e99f7-145d-4e18-9c86-067da6344b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_HorizontalScrollContainer_0']/div/div/div/div/div/div[2]/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>4201ef63-0da5-4b15-8843-5b4390ccc4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a4e3f8af-1cdb-4e04-bed1-ebadfd3d0c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = '100.TaxiRequisition.LoginPage.passwordTextBox2']</value>
      <webElementGuid>a3f575f1-7ec0-4ce9-9a17-c1c33f348774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
