<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_100.TaxiRequisition.LoginPag_69ed09</name>
   <tag></tag>
   <elementGuidId>9948a637-4cea-4d01-b5b7-b316cf73aa76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='100.TaxiRequisition.LoginPage.loginIdTextBox2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f17562c-c897-4c52-a43f-0cdb23cc8a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd74ed57-96ed-4979-a9be-4fd1bf496f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>100.TaxiRequisition.LoginPage.loginIdTextBox2</value>
      <webElementGuid>fedc8a03-9b6c-4983-b315-111f9c9f750b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>54f2d05f-8b58-4a47-9a5c-f323d3c217e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad00d71d-7383-4930-9614-50b94a165ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e9b02f3-c6ab-41fd-964d-9638218607f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>00332c91-0d3d-41c6-84d5-a9b25dd0fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;100.TaxiRequisition.LoginPage.loginIdTextBox2&quot;)</value>
      <webElementGuid>e0cd9f88-b208-4c7c-abba-b30b732e96eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='100.TaxiRequisition.LoginPage.loginIdTextBox2']</value>
      <webElementGuid>43e03509-3b02-4935-b357-30536d5288ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_HorizontalScrollContainer_0']/div/div/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>fb6d2c3a-060b-4f35-bb54-f9f76f108de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cf7ded4d-261c-4484-aa10-6c71a7fcc06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '100.TaxiRequisition.LoginPage.loginIdTextBox2']</value>
      <webElementGuid>b4cdcb3f-e639-42be-a9dc-f68725a52d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
